// SPEC-009 Phase 3 — T015 (Runtime Smoke).
//
// This test proves that the wrapper generated by `installIntegration` actually
// loads the compiled Runtime Guard and produces the correct ALLOW / ASK / DENY
// decisions through the real OpenCode plugin harness shape
// (`tool.execute.before`, `command.execute.before`, `permission.ask`).
//
// The wrapper is imported via `pathToFileURL` from the disposable repo's
// `.opencode/plugins/changebudget.js`. It re-exports the compiled plugin
// module, so loading the wrapper is loading the Runtime Guard itself.

import * as assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { test } from 'node:test';

import {
  MANAGED_RESOURCES,
  installIntegration,
  resolveChangeBudgetRoot,
} from '../../src/core/integration/opencode.js';
import { RUNTIME_RULES } from '../../opencode-plugin/src/projection.js';

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

const REPO_PREFIX = 'cb-int-opencode-runtime-';

function runGit(root: string, args: string[]): void {
  const result = spawnSync('git', args, { cwd: root, encoding: 'utf8' });
  if (result.status !== 0) {
    throw new Error(`git ${args.join(' ')} failed: ${result.stderr}`);
  }
}

async function createDisposableRepo(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), REPO_PREFIX));
  runGit(root, ['init']);
  runGit(root, ['config', 'user.name', 'integration test']);
  runGit(root, ['config', 'user.email', 'integration@test']);
  runGit(root, ['commit', '--allow-empty', '-m', 'seed']);
  return root;
}

async function cleanup(root: string): Promise<void> {
  if (existsSync(root)) {
    await rm(root, { recursive: true, force: true });
  }
}

interface CliResult {
  status: number | null;
  stdout: string;
  stderr: string;
}

function runCliCommand(root: string, command: string, args: string[] = []): CliResult {
  const cliPath = join(process.cwd(), 'dist', 'src', 'cli', 'index.js');
  const result = spawnSync(process.execPath, [cliPath, command, ...args], {
    cwd: root,
    encoding: 'utf8',
  });
  return {
    status: result.status,
    stdout: result.stdout ?? '',
    stderr: result.stderr ?? '',
  };
}

interface PluginHooks {
  'tool.execute.before'?: (
    input: { tool: string; sessionID: string; callID: string },
    output: { args: unknown },
  ) => Promise<void>;
  'command.execute.before'?: (
    input: { command: string; sessionID: string; arguments: string },
  ) => Promise<void>;
  'permission.ask'?: (
    input: Record<string, unknown> & { sessionID: string; callID?: string },
    output: { status: 'allow' | 'deny' | 'ask' },
  ) => Promise<void>;
}

interface WrapperModule {
  id?: string;
  server: (input: { directory: string; worktree: string }) => Promise<PluginHooks>;
}

/**
 * Import the wrapper generated by `installIntegration` at
 * `.opencode/plugins/changebudget.js` and call `server()` to get the hooks.
 *
 * The wrapper re-exports the compiled Runtime Guard via
 * `export { default } from "<file_url>";` so loading it loads the
 * compiled Runtime Guard module.
 */
async function loadInstalledWrapper(repositoryRoot: string): Promise<PluginHooks> {
  const wrapperPath = join(repositoryRoot, MANAGED_RESOURCES.pluginWrapper);
  const moduleUrl = pathToFileURL(wrapperPath).href;
  const wrapperModule = (await import(moduleUrl)) as { default: WrapperModule };
  const wrapper = wrapperModule.default;
  assert.ok(typeof wrapper.server === 'function', 'wrapper.default.server must be a function');
  return wrapper.server({ directory: repositoryRoot, worktree: repositoryRoot });
}

function metadata(): Record<string, unknown> {
  return {};
}

async function initAndStartAllowPathsContract(repositoryRoot: string): Promise<void> {
  await mkdir(join(repositoryRoot, 'src'), { recursive: true });
  await initAndStartContractInternal(repositoryRoot, ['src/**']);
}

async function initAndStartAllowPathsWithDependenciesContract(repositoryRoot: string): Promise<void> {
  // Allow-list includes `package.json` so that a `npm install` command
  // reaches the dependency-sensitive rule (OCG-SENSITIVE-DEPENDENCIES)
  // instead of being shadowed by OCG-PATH-OUT-SCOPE.
  await initAndStartContractInternal(repositoryRoot, ['src/**', 'package.json']);
}

async function initAndStartContractInternal(repositoryRoot: string, allowPaths: string[]): Promise<void> {
  // Commit the integration-managed files so they do NOT count as part of
  // the contract's diff. The Runtime Guard's `runCheck` is invoked on
  // every `permission.ask` call; if the integration files are untracked,
  // any restricted `--allow-paths` will reject them as out-of-scope and
  // the resulting REPAIR decision shadows every more specific rule.
  runGit(repositoryRoot, [
    'add',
    MANAGED_RESOURCES.pluginWrapper,
    MANAGED_RESOURCES.instructions,
    MANAGED_RESOURCES.opencodeConfig,
  ]);
  runGit(repositoryRoot, ['commit', '-m', 'baseline integration files']);

  const initResult = runCliCommand(repositoryRoot, 'init');
  assert.equal(initResult.status, 0, `init failed: ${initResult.stderr}`);

  const startResult = runCliCommand(repositoryRoot, 'start', [
    '--task', 'runtime smoke',
    '--base-revision', 'HEAD',
    '--allow-paths', allowPaths.join(','),
    '--allow-new-files',
  ]);
  assert.equal(startResult.status, 0, `start failed: ${startResult.stderr}`);
}

// ---------------------------------------------------------------------------
// T015 — Wrapper import + Runtime Guard smoke
// ---------------------------------------------------------------------------

test('T015: installed wrapper loads via pathToFileURL and exposes the three expected hooks', async () => {
  const root = await createDisposableRepo();
  try {
    const install = await installIntegration(root, resolveChangeBudgetRoot());
    assert.equal(install.readiness, 'READY');

    // The wrapper file actually exists on disk under the managed path.
    const wrapperPath = join(root, MANAGED_RESOURCES.pluginWrapper);
    assert.equal(existsSync(wrapperPath), true, 'wrapper file must exist on disk');

    const hooks = await loadInstalledWrapper(root);

    assert.equal(typeof hooks['tool.execute.before'], 'function', 'tool.execute.before hook is required');
    assert.equal(typeof hooks['command.execute.before'], 'function', 'command.execute.before hook is required');
    assert.equal(typeof hooks['permission.ask'], 'function', 'permission.ask hook is required');
  } finally {
    await cleanup(root);
  }
});

test('T015: wrapper default export carries the Runtime Guard plugin id', async () => {
  const root = await createDisposableRepo();
  try {
    await installIntegration(root, resolveChangeBudgetRoot());

    const wrapperPath = join(root, MANAGED_RESOURCES.pluginWrapper);
    const moduleUrl = pathToFileURL(wrapperPath).href;
    const wrapperModule = (await import(moduleUrl)) as { default: WrapperModule };

    // The Runtime Guard plugin module is { id, server }.
    assert.ok(wrapperModule.default, 'wrapper.default must be exported');
    assert.ok(typeof wrapperModule.default.server === 'function', 'default.server must be a function');
  } finally {
    await cleanup(root);
  }
});

test('T015: ALLOW — write to an in-scope path produces allow / OCG-ALLOW', async () => {
  const root = await createDisposableRepo();
  try {
    await installIntegration(root, resolveChangeBudgetRoot());
    await initAndStartAllowPathsContract(root);

    const hooks = await loadInstalledWrapper(root);

    const sessionID = 'session-runtime-allow';
    const callID = 'call-runtime-allow';
    await hooks['tool.execute.before']!(
      { tool: 'write', sessionID, callID },
      { args: { path: 'src/app.ts' } },
    );

    const permission = {
      sessionID,
      callID,
      type: 'tool',
      pattern: 'write',
      metadata: metadata(),
    };
    const output = { status: 'deny' as const };

    await hooks['permission.ask']!(permission, output);

    assert.equal(output.status, 'allow');
    assert.equal(permission.metadata?.rule, RUNTIME_RULES.ALLOW);
    assert.equal(permission.metadata?.runtimeAction, 'allow');
    assert.equal(permission.metadata?.targetPath, 'src/app.ts');
  } finally {
    await cleanup(root);
  }
});

test('T015: ASK — write to an out-of-scope path produces ask / OCG-PATH-OUT-SCOPE', async () => {
  const root = await createDisposableRepo();
  try {
    await mkdir(join(root, 'tests'), { recursive: true });
    await writeFile(join(root, 'tests', 'contract.spec.ts'), 'export {};\n', 'utf8');
    await installIntegration(root, resolveChangeBudgetRoot());
    await initAndStartAllowPathsContract(root);

    const hooks = await loadInstalledWrapper(root);

    const sessionID = 'session-runtime-ask';
    const callID = 'call-runtime-ask';
    await hooks['tool.execute.before']!(
      { tool: 'write', sessionID, callID },
      { args: { path: 'tests/contract.spec.ts' } },
    );

    const permission = {
      sessionID,
      callID,
      type: 'tool',
      pattern: 'write',
      metadata: metadata(),
    };
    const output = { status: 'allow' as const };

    await hooks['permission.ask']!(permission, output);

    assert.equal(output.status, 'ask');
    assert.equal(permission.metadata?.rule, RUNTIME_RULES.OUT_SCOPE);
    assert.equal(permission.metadata?.runtimeAction, 'ask');
    assert.equal(permission.metadata?.targetPath, 'tests/contract.spec.ts');
  } finally {
    await cleanup(root);
  }
});

test('T015: DENY (unresolved) — write with empty args produces deny / OCG-UNRESOLVED-MUTATION', async () => {
  const root = await createDisposableRepo();
  try {
    await installIntegration(root, resolveChangeBudgetRoot());
    await initAndStartAllowPathsContract(root);

    const hooks = await loadInstalledWrapper(root);

    const sessionID = 'session-runtime-unresolved';
    const callID = 'call-runtime-unresolved';
    await hooks['tool.execute.before']!(
      { tool: 'write', sessionID, callID },
      { args: {} },
    );

    const permission = {
      sessionID,
      callID,
      type: 'tool',
      pattern: 'write',
      metadata: metadata(),
    };
    const output = { status: 'allow' as const };

    await hooks['permission.ask']!(permission, output);

    assert.equal(output.status, 'deny');
    assert.equal(permission.metadata?.rule, RUNTIME_RULES.UNRESOLVED_MUTATION);
    assert.equal(permission.metadata?.runtimeAction, 'block');
    assert.equal(permission.metadata?.isTargetResolved, false);
  } finally {
    await cleanup(root);
  }
});

test('T015: DENY (.changebudget protection) — edit to .changebudget/state.json produces deny / OCG-CHANGEBUDGET-PROTECT', async () => {
  const root = await createDisposableRepo();
  try {
    await installIntegration(root, resolveChangeBudgetRoot());
    await initAndStartAllowPathsContract(root);

    const hooks = await loadInstalledWrapper(root);

    const sessionID = 'session-runtime-budget';
    const callID = 'call-runtime-budget';
    await hooks['tool.execute.before']!(
      { tool: 'edit', sessionID, callID },
      { args: { path: '.changebudget/state.json' } },
    );

    const permission = {
      sessionID,
      callID,
      type: 'tool',
      pattern: 'edit',
      metadata: metadata(),
    };
    const output = { status: 'allow' as const };

    await hooks['permission.ask']!(permission, output);

    assert.equal(output.status, 'deny');
    assert.equal(permission.metadata?.rule, RUNTIME_RULES.CHANGEBUDGET);
    assert.equal(permission.metadata?.runtimeAction, 'block');
    assert.equal(permission.metadata?.targetPath, '.changebudget/state.json');
  } finally {
    await cleanup(root);
  }
});

test('T015: command hook — npm install command goes through the wrapper and asks for dependency-sensitive write', async () => {
  const root = await createDisposableRepo();
  try {
    await installIntegration(root, resolveChangeBudgetRoot());
    await initAndStartAllowPathsWithDependenciesContract(root);

    const hooks = await loadInstalledWrapper(root);

    const sessionID = 'session-runtime-command';
    await hooks['command.execute.before']!({
      command: 'npm',
      sessionID,
      arguments: 'install left-pad',
    });

    const permission = {
      sessionID,
      type: 'command',
      pattern: 'command',
      metadata: metadata(),
    };
    const output = { status: 'allow' as const };

    await hooks['permission.ask']!(permission, output);

    assert.equal(output.status, 'ask');
    assert.equal(permission.metadata?.rule, RUNTIME_RULES.DEPENDENCIES);
    assert.equal(permission.metadata?.targetPath, 'package.json');
  } finally {
    await cleanup(root);
  }
});

test('T015: wrapper never touches .changebudget state.json itself when it loads', async () => {
  const root = await createDisposableRepo();
  try {
    // Initialize the repository through ChangeBudget so .changebudget/state.json exists.
    const initResult = runCliCommand(root, 'init');
    assert.equal(initResult.status, 0);

    const statePath = join(root, '.changebudget', 'state.json');
    assert.equal(existsSync(statePath), true);
    const stateBefore = await readFile(statePath, 'utf8');

    await installIntegration(root, resolveChangeBudgetRoot());

    const stateAfter = await readFile(statePath, 'utf8');
    assert.equal(stateAfter, stateBefore, 'installing the integration must not mutate .changebudget state.json');

    // Load the wrapper — loading must not mutate .changebudget state either.
    await loadInstalledWrapper(root);

    const stateAfterLoad = await readFile(statePath, 'utf8');
    assert.equal(stateAfterLoad, stateBefore, 'loading the wrapper must not mutate .changebudget state.json');

    // No `.changebudget` directory may be created from a no-Spec-Kit repo
    // that never had `init` — but since we did `init`, we only assert
    // identity here. The "no state creation from integration" guarantee is
    // covered in `integration-opencode-invariants.test.ts`.
  } finally {
    await cleanup(root);
  }
});

test('T015: wrapper installation does not modify AGENTS.md content in the disposable repo', async () => {
  const root = await createDisposableRepo();
  try {
    const agentsContent = '# Project AGENTS guidance\n\nThis file is owned by the user and must never be modified by tooling.\n';
    await mkdir(join(root), { recursive: true });
    await writeFile(join(root, 'AGENTS.md'), agentsContent, 'utf8');
    runGit(root, ['add', 'AGENTS.md']);
    runGit(root, ['commit', '-m', 'seed AGENTS.md']);

    const agentsBefore = await readFile(join(root, 'AGENTS.md'), 'utf8');

    await installIntegration(root, resolveChangeBudgetRoot());
    await loadInstalledWrapper(root);

    const agentsAfter = await readFile(join(root, 'AGENTS.md'), 'utf8');
    assert.equal(agentsAfter, agentsBefore, 'AGENTS.md must be byte-identical after install + wrapper load');
  } finally {
    await cleanup(root);
  }
});

test('T015: removed integration — wrapper file is deleted and no longer resolvable', async () => {
  const root = await createDisposableRepo();
  try {
    const { removeIntegration } = await import('../../src/core/integration/opencode.js');

    await installIntegration(root, resolveChangeBudgetRoot());

    const wrapperPath = join(root, MANAGED_RESOURCES.pluginWrapper);
    assert.equal(existsSync(wrapperPath), true);

    const removeResult = await removeIntegration(root);
    assert.equal(removeResult.readiness, 'READY');
    assert.equal(removeResult.resources.pluginWrapper.action, 'REMOVE');

    assert.equal(existsSync(wrapperPath), false, 'wrapper file must be deleted by remove');

    // After removal, importing the wrapper path should fail.
    const moduleUrl = pathToFileURL(wrapperPath).href;
    await assert.rejects(
      async () => {
        await import(moduleUrl);
      },
      (error: unknown) => {
        // Module not found errors are expected.
        assert.ok(error instanceof Error, 'expected an Error to be thrown');
        return true;
      },
    );
  } finally {
    await cleanup(root);
  }
});
